- hosts: localhost
  become: True

  tasks:
  ## 基本のセットアップをしてみよう
  - name: install docker
    dnf:
      name: docker
    when:
      - ansible_distribution == 'Amazon'
      - ansible_distribution_major_version == "2023"

  - name: install docker
    yum:
      name: docker
    when:
      - ansible_distribution == 'Amazon'
      - ansible_distribution_major_version != "2023"

  - name: install docker-compose binary
    shell: 'curl -L https://github.com/docker/compose/releases/download/v2.19.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }} > /usr/local/bin/docker-compose'

  - name: change permission "/usr/local/bin/docker-compose"
    file:
      path: /usr/local/bin/docker-compose
      mode: 0755

  - name: install epel
    shell: amazon-linux-extras install epel
    when: 
      - ansible_distribution == 'Amazon'
      - ansible_distribution_major_version != "2023"

  - name: install require package
    dnf:
      name: '{{ require_packages }}'
    vars:
      require_packages:
        - nginx
        - git
    when:
      - ansible_distribution == 'Amazon'
      - ansible_distribution_major_version == "2023"

  - name: install require package
    yum:
      name: '{{ require_packages }}'
    vars:
      require_packages:
        - nginx
        - git
    when:
      - ansible_distribution == 'Amazon'
      - ansible_distribution_major_version != "2023"

  ## mattermostを起動してみよう
  - name: git clone
    git:
      repo: https://github.com/mattermost/docker
      dest: /opt/mattermost

  - name: copy .env
    copy:
      remote_src: true
      src: /opt/mattermost/env.example
      dest: /opt/mattermost/.env

  - name: edit .env
    replace:
      path: /opt/mattermost/.env
      regexp: 'mm.example.com'
      replace: '{{ MY_DOMAIN }}'

  - name: make directorys
    file: 
      path: '/opt/mattermost/volumes/app/mattermost/{{ item }}'
      state: directory
      owner: root
      group: root
      mode: 0775
    vars:
      item: 
        - config
        - data
        - plugins
        - cluent/plugins
        - bleve-indexes

  - name: '/opt/mattermost/volumes/app/mattermost/config'
    file: 
      path: '/opt/mattermost/volumes/app/mattermost/config'
      state: directory
      owner: 2000
      group: 2000
      mode: 0775

  - name: put mattermost-docker.service
    copy:
      src: ./files/mattermost-docker.service
      dest: /usr/lib/systemd/system/mattermost-docker.service
      owner: root
      group: root
      mode: 0664

  - name: start mattermost
    systemd:
      name: mattermost-docker.service
      state: started
      daemon_reload: true
      enabled: true

  ## nginx を前段に置いてみよう
  - name: config nginx
    template:
      src: ./templates/mattermost_nginx.conf
      dest: '/etc/nginx/conf.d/{{ MY_DOMAIN }}.conf'
      owner: root
      group: root
      mode: 0664

  - name: put htaccess
    copy:
      src: ./files/.htpasswd
      dest: /etc/nginx/conf.d/
      owner: root
      group: root
      mode: 0664

  - name: make logdir
    file:
      path: '/var/log/{{ MY_DOMAIN }}'
      state: directory
      owner: root
      group: root
      mode: 0775

  - name: start nginx
    systemd:
      name: nginx
      state: started
      enabled: true

  vars_files:
    - vars/vars.yml
